version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y

  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html/

  post_build:
    commands:
      - echo Configuring NGINX
      - sudo systemctl start nginx  # If you want to start the service
      - sudo systemctl enable nginx  # To enable it on boot

artifacts:
  files:
    - /var/www/html/index.html